// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// Operation is the predicate function for operation builders.
type Operation func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleOperation is the predicate function for roleoperation builders.
type RoleOperation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
