// Code generated by ent, DO NOT EDIT.

package model

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the model type in the database.
	Label = "model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeOperations holds the string denoting the operations edge name in mutations.
	EdgeOperations = "operations"
	// Table holds the table name of the model in the database.
	Table = "models"
	// OperationsTable is the table that holds the operations relation/edge.
	OperationsTable = "operations"
	// OperationsInverseTable is the table name for the Operation entity.
	// It exists in this package in order to avoid circular dependency with the "operation" package.
	OperationsInverseTable = "operations"
	// OperationsColumn is the table column denoting the operations relation/edge.
	OperationsColumn = "model_id"
)

// Columns holds all SQL columns for model fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Model queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByOperationsCount orders the results by operations count.
func ByOperationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOperationsStep(), opts...)
	}
}

// ByOperations orders the results by operations terms.
func ByOperations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOperationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOperationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OperationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OperationsTable, OperationsColumn),
	)
}
